# Generated by Django 3.0.2 on 2020-01-10 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0002_auto_20200110_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='phone',
            field=models.IntegerField(default=0),
        ),
    ]
