# Generated by Django 3.0.2 on 2020-01-11 06:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crops', '0004_auto_20200110_2000'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonFinancial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=10)),
                ('username', models.CharField(default='', max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('contact', models.IntegerField(default=0)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=1)),
                ('firmname', models.CharField(max_length=50)),
                ('employee', models.CharField(max_length=25)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Financial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=10)),
                ('username', models.CharField(default='', max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('contact', models.IntegerField(default=0)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=1)),
                ('firmname', models.CharField(max_length=50)),
                ('employee', models.CharField(max_length=25)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
