# Generated by Django 3.0.2 on 2020-01-11 06:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crops', '0005_financial_nonfinancial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputcrops',
            name='farmer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
