# Generated by Django 3.0.2 on 2020-01-11 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0006_inputcrops_farmer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inputcrops',
            name='region',
        ),
    ]
